### ISSUE TITLE
Add a weapon for Magnus: Bullets.

### ISSUE THREAD

**Issue by karandesai-96** [karandesai-96/Magneto-Mania#8]
This issue focuses on setting up the first weapon for Magnus after setting the basic gameplay.

Goals for this PR (one after another) are:
- Set up a class which makes a single bullet object first.
    - Use the logic of recently developed **Magnus.java** class as the bullet has a similar trajectory. It just doesn't stop and leaves the screen - this is the only difference.
- Make Magnus shoot a single bullet to the finger, whenever at reset on the wall.
    - Look for the pre-existing code: GameView.java. Make a **BulletController.java** having structure similar to **MagnusController.java**.

More objectives would be added in subsequent comments after these two are accomplished.

**Comment by hareshkh** [comment]
This issue is referenced in #11. Bullet and BulletController class have been successfully implemented. Magnus is shooting one bullet at the target.

**Comment by hareshkh** [comment]
This issue is resolved with the merging of #12
